// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Reporting-Prototype",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Reporting-Prototype",
            targets: ["AppModule"],
            bundleIdentifier: "com.ruka.reporting-prototype",
            teamIdentifier: "U2FX3W9AAW",
            displayVersion: "0.1",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.brown),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/techprimate/TPPDF.git", "2.6.1"..<"3.0.0"),
        .package(url: "https://github.com/Fahrenberg/ImageCompressionKit.git", "2.3.3"..<"3.0.0"),
        .package(url: "https://github.com/Fahrenberg/Extensions.git", "4.0.0"..<"5.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "TPPDF", package: "TPPDF"),
                .product(name: "ImageCompressionKit", package: "ImageCompressionKit"),
                .product(name: "Extensions", package: "Extensions")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
